# Generated by Django 2.1.5 on 2019-11-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_return'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='article_title',
            new_name='name_title',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='article_text',
            new_name='sum_title',
        ),
        migrations.RenameField(
            model_name='return',
            old_name='pub_date',
            new_name='date',
        ),
    ]
