# Generated by Django 2.1.5 on 2019-11-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20191111_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Return',
        ),
    ]
