# Generated by Django 2.1.5 on 2019-11-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20191111_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='article_title',
            new_name='credit_title',
        ),
    ]
