# Generated by Django 2.1.5 on 2019-10-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191028_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='credit_text',
            new_name='article_text',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='credit_title',
            new_name='article_title',
        ),
    ]
